---

dist: xenial
language: python
python: 3.8.3
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - black --line-length=79 --check .
  - pytest
  - pytest --cov=programs --cov-fail-under=0
after_success:
  - coveralls
env:
  - PYTHONBREAKPOINT=0
